<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-18 at 10:08:58.
 */

require __DIR__ . "/../StringCalculator.php";

class StringCalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var StringCalculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringCalculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testIsEmpty(){
        $this->assertEquals(0,$this->object->Add(""));
    }
    public function testOneNumber(){
        $this->assertEquals(1,$this->object->Add("1"));
    }
    public function testTwoNumbers(){
        $this->assertEquals(3,$this->object->Add("1,2"));
    }

}
